In [6]:
import pandas as pd

In [2]:
df = pd.read_csv('eksport_danych.csv')

In [3]:
df.head()

,ID,Title,Category,Attack Type,Scenario Description,Tools Used,Attack Steps,Target Type,Vulnerability,MITRE Technique,Impact,Detection Method,Solution,Tags,Source,Unnamed: 15
0,1,Authentication Bypass via SQL Injection,Mobile Security,SQL Injection (SQLi),A login form fails to validate or sanitize inp...,"Browser, Burp Suite, SQLMap",1. Reconnaissance: Find a login form on the we...,"Web Login Portals (e.g., banking, admin dashbo...",Unsanitized input fields in SQL queries,"T1078 (Valid Accounts), T1190 (Exploit Public-...","Full account takeover, data theft, privilege e...","Web server logs, anomaly detection (e.g., logi...","Use prepared statements, Sanitize inputs, Limi...","SQLi, Authentication Bypass, Web Security, OWA...","OWASP, MITRE ATT&CK, DVWA",NaN
1,2,Union-Based SQL Injection,AI Agents & LLM Exploits,SQL Injection,This attack occurs when a hacker uses the SQL ...,"SQLMap, Burp Suite, Havij, Browser Developer T...",1. Identify User Input Points: Attacker finds ...,"Web Applications, Login Pages, Search Forms",Improperly filtered input fields that allow SQ...,T1190 – Exploit Public-Facing Application,"Data leakage, Credential theft, Account takeov...",Web Application Firewalls (WAF)Log AnalysisInp...,Use parameterized queries (Prepared Statements...,#SQLInjection #WebSecurity #UnionAttack #OWASP...,"OWASP, MITRE ATT&CK, Acunetix, PortSwigger Web...",NaN
2,3,Error-Based SQL Injection,AI Agents & LLM Exploits,SQL Injection,This attack occurs when an attacker intentiona...,"SQLMap, Burp Suite, Manual Browser Testing, Havij",1. Identify Input Points:Attacker finds a fiel...,"Web Applications, Login Forms, URL Parameters,...",Error message exposure due to lack of input va...,T1190 – Exploit Public-Facing Application,"Information disclosure, Database structure exp...",Review and monitor error logsEnable generic er...,Turn off detailed error messages in production...,#SQLInjection #ErrorLeakage #WebAppSecurity #O...,"OWASP, MITRE ATT&CK, Acunetix, PortSwigger Web...",NaN
3,4,Blind SQL Injection,AI Agents & LLM Exploits,SQL Injection,"In Blind SQL Injection, the attacker doesn’t s...","SQLMap, Burp Suite, sqlninja, Manual Browser T...",1. Find a User Input Point:Attacker finds a pl...,"Web Applications, Login Pages, Search Fields, ...","No error messages, but user input is still pas...",T1190 – Exploit Public-Facing Application,Slow and stealthy data theftFull database comp...,Monitor for slow and repetitive requestsAnalyz...,Use parameterized queries (prepared statements...,#BlindSQLi #TimeBasedSQLi #WebAppSecurity #OWA...,"OWASP, MITRE ATT&CK, Acunetix, PortSwigger, SQ...",NaN
4,5,Second-Order SQL Injection,AI Agents & LLM Exploits,SQL Injection,"In a Second-Order SQL Injection, the attacker ...","Burp Suite, SQLMap, Postman, Browser Dev Tools...",1. Identify Stored Input Fields:The attacker l...,"Web Applications, User Registration Forms, Pro...",Trusting previously stored unvalidated data in...,T1505.003 – SQL Injection,Delayed data theftUnexpected system behaviorSe...,Log monitoring for delayed query failuresTrack...,Sanitize and validate inputs both at entry and...,#SecondOrderSQLi #DelayedInjection #StoredInje...,"OWASP, MITRE ATT&CK, PortSwigger Academy, Acun...",NaN

In [8]:
df.describe(include='all')

,ID,Title,Category,Attack Type,Scenario Description,Tools Used,Attack Steps,Target Type,Vulnerability,MITRE Technique,Impact,Detection Method,Solution,Tags,Source,Unnamed: 15
count,14133.000000,14133,14133,14133,14133,14119,14133,14129,14115,14109,14130,14129,14130,14130,13973,46
unique,NaN,13793,64,8834,13866,12935,13895,9885,13424,5770,13187,13813,13852,13817,7051,2
top,NaN,Beacon Over HTTPS via Cobalt Strike,Insider Threat,Hardware Interface Exploitation,Establishes C2 using DNS queries to bypass out...,Velociraptor,1. Record multiple command sessions between sa...,Windows,PLC,T1203,Credential theft,Registry + Prefetch + Memory,Disable debug ports in production,"GPS spoofing, mobile fraud",Simulated,Educational Simulation
freq,NaN,3,569,161,3,18,3,291,21,343,37,9,4,4,2347,45
mean,7067.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,4079.990012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,3534.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,7067.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,10600.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,14133.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.describe()

                 ID
count  14133.000000
mean    7067.000000
std     4079.990012
min        1.000000
25%     3534.000000
50%     7067.000000
75%    10600.000000
max    14133.000000

In [19]:
df.dtypes

ID                       int64
Title                   object
Category                object
Attack Type             object
Scenario Description    object
Tools Used              object
Attack Steps            object
Target Type             object
Vulnerability           object
MITRE Technique         object
Impact                  object
Detection Method        object
Solution                object
Tags                    object
Source                  object
Unnamed: 15             object
dtype: object

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14133 entries, 0 to 14132
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    14133 non-null  int64
 1   Title                 14133 non-null  object
 2   Category              14133 non-null  object
 3   Attack Type           14133 non-null  object
 4   Scenario Description  14133 non-null  object
 5   Tools Used            14119 non-null  object
 6   Attack Steps          14133 non-null  object
 7   Target Type           14129 non-null  object
 8   Vulnerability         14115 non-null  object
 9   MITRE Technique       14109 non-null  object
 10  Impact                14130 non-null  object
 11  Detection Method      14129 non-null  object
 12  Solution              14130 non-null  object
 13  Tags                  14130 non-null  object
 14  Source                13973 non-null  object
 15  Unnamed: 15           46 non-null     object
dtypes: int64(1), object(15)
memory usage: 1.7+ MB

In [13]:
df.nunique()

ID                      14133
Title                   13793
Category                   64
Attack Type              8834
Scenario Description    13866
Tools Used              12935
Attack Steps            13895
Target Type              9885
Vulnerability           13424
MITRE Technique          5770
Impact                  13187
Detection Method        13813
Solution                13852
Tags                    13817
Source                   7051
Unnamed: 15                 2
dtype: int64

In [14]:
df['Category'].unique()

array([' Mobile Security', 'AI Agents & LLM Exploits', 'AI/ML Security',
       'Cloud Security', 'Mobile Security', 'Network Security',
       'Operating System Exploits', 'Network security',
       'Web Application Security', 'AI Data Leakage & Privacy Risks',
       'Blockchain / Web3', 'Cryptography Attacks', 'SCADA/ICS',
       'IoT / Embedded Devices', 'Insider Threat',
       'Physical / Hardware Attacks', 'Malware & Threat',
       'Email & Messaging Protocol Exploits',
       'Wireless Attacks (Advanced)',
       'Quantum Cryptography & Post-Quantum Threats', 'Red Team',
       'Blue Team', 'DevSecOps & CI/CD Security',
       'Virtualization & Container Security → Defensive Evasion & Persistence → 🛡️ Evading Container Security Tools',
       'Browser Security → Cross-Site Scripting (XSS)',
       'Browser Security → Clickjacking / UI Redressing',
       'Browser Security → Tabnabbing / Tab Hijacking',
       'Browser Security → SOP (Same-Origin Policy) Bypass',
       'Browser Security → Browser Extension Abuse',
       'Browser Security → Cookie Theft & Session Hijacking',
       'Browser Security → WebAssembly (WASM) Abuse',
       'Browser Security → Client-Side CSRF',
       'Browser Security → Browser Fingerprinting / Tracking',
       'Browser Security → Defense Strategies (Blue Team)',
       'Supply Chain Attacks',
       'Supply Chain Attacks → Dependency Confusion & Malicious Libraries',
       'Supply Chain Attacks → Dependency Confusion', 'DFIR',
       'Zero-Day Research / Fuzzing',
       'Zero-Day Research / Fuzzing → Target Reconnaissance & Environment Setup',
       'Zero-Day Research / Fuzzing → Fuzzer Configuration',
       'Zero-Day Research / Fuzzing → Reverse Engineering the Binary',
       'Zero-Day Research / Fuzzing → Vulnerability Classification',
       'Zero-Day Research / Fuzzing → Exploit Development (Optional / Advanced)',
       'Zero-Day Research / Fuzzing → Exploit Development',
       'Zero-Day Research / Fuzzing → Automation and Scaling',
       'Zero-Day Research / Fuzzing → Reporting & Responsible Disclosure',
       'Automotive / Cyber-Physical Systems',
       'Automotive / Cyber-Physical Systems → CAN Bus Injection',
       'Automotive / Cyber-Physical Systems → Infotainment System Hacking',
       'Automotive / CPS',
       'Automotive / Cyber-Physical Systems → ECU Reverse Engineering',
       'Automotive / Cyber-Physical Systems → Sensor Spoofing & Physical Layer Attacks',
       'Automotive / CPS → Sensor Spoofing & Physical Layer Attacks',
       'Automotive / CPS → Sensor Spoofing',
       'Automotive / CPS → Physical Layer Attack',
       'Automotive / Cyber-Physical Systems → Wireless Communication Attacks',
       'Automotive / Cyber-Physical Systems → Remote Keyless Entry Exploits',
       'Automotive / Cyber-Physical Systems → Firmware Over-The-Air (FOTA) Abuse',
       'Automotive / CPS → Firmware Over-The-Air (FOTA) Abuse',
       'Automotive / Cyber-Physical Systems → Vehicle Control Manipulation',
       'Automotive / Cyber-Physical Systems → Vehicle Control Manipulation (Safety-Critical)',
       'Automotive / Cyber-Physical Systems → Defensive & Real-Time Monitoring Tactics',
       'Satellite & Space Infrastructure Security'], dtype=object)

In [15]:
df['Category'].value_counts()

Category
Insider Threat                                                   569
Physical / Hardware Attacks                                      548
Quantum Cryptography & Post-Quantum Threats                      542
Wireless Attacks (Advanced)                                      535
Malware & Threat                                                 528
                                                                ...
Automotive / Cyber-Physical Systems → ECU Reverse Engineering      7
Automotive / CPS → Firmware Over-The-Air (FOTA) Abuse              5
Automotive / CPS → Physical Layer Attack                           3
Network security                                                   2
 Mobile Security                                                   1
Name: count, Length: 64, dtype: int64

In [21]:
df.isnull().sum()

ID                          0
Title                       0
Category                    0
Attack Type                 0
Scenario Description        0
Tools Used                 14
Attack Steps                0
Target Type                 4
Vulnerability              18
MITRE Technique            24
Impact                      3
Detection Method            4
Solution                    3
Tags                        3
Source                    160
Unnamed: 15             14087
dtype: int64

In [24]:
df.columns

Index(['ID', 'Title', 'Category', 'Attack Type', 'Scenario Description',
       'Tools Used', 'Attack Steps ', 'Target Type', 'Vulnerability',
       'MITRE Technique', 'Impact', 'Detection Method', 'Solution', 'Tags',
       'Source', 'Unnamed: 15'],
      dtype='object')

In [25]:
df['Attack Steps '].str.rstrip()

0        1. Reconnaissance: Find a login form on the we...
1        1. Identify User Input Points: Attacker finds ...
2        1. Identify Input Points:Attacker finds a fiel...
3        1. Find a User Input Point:Attacker finds a pl...
4        1. Identify Stored Input Fields:The attacker l...
                               ...
14128    1. Simulate spoofed and legitimate satellite t...
14129    1. Host a multi-agency workshop including mili...
14130    1. Design a containerized satellite simulation...
14131    1. Create a firmware scanning tool targeting s...
14132    1. Identify cyber standards applicable to sate...
Name: Attack Steps , Length: 14133, dtype: object

In [27]:
df.columns = df.columns.str.strip()

In [28]:
print(df.columns.tolist())

['ID', 'Title', 'Category', 'Attack Type', 'Scenario Description', 'Tools Used', 'Attack Steps', 'Target Type', 'Vulnerability', 'MITRE Technique', 'Impact', 'Detection Method', 'Solution', 'Tags', 'Source', 'Unnamed: 15']

In [31]:
df = df.drop('Unnamed: 15', axis = 1)

In [33]:
df.head(0)

Empty DataFrame
Columns: [ID, Title, Category, Attack Type, Scenario Description, Tools Used, Attack Steps, Target Type, Vulnerability, MITRE Technique, Impact, Detection Method, Solution, Tags, Source]
Index: []